version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "aps831"
    labels:
      - "github_actions"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
