# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Hardcoding Validation
on:
  workflow_dispatch:
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3.2.0

      - name: run hardcoding validation script
        run: ./hardcoding_validation.sh
