name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
jobs:
  publish:
    permissions:
      contents: write
    uses: aps831/workflows/.github/workflows/release.yaml@master
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
